2019-06-27 18:53:15,125 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:50]
2019-06-27 18:54:07,217 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:50]
2019-06-27 18:55:41,711 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:50]
2019-06-27 18:57:17,924 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:50]
2019-06-27 23:07:08,290 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:52]
2019-07-02 14:38:11,974 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:59]
2019-07-02 14:38:21,043 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:59]
2019-07-02 15:01:14,729 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:59]
2019-07-02 17:21:24,176 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:72]
2019-07-02 17:21:27,161 ERROR: Exception on / [GET] [in /home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1830, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2106, in preprocess_request
    rv = func()
  File "/home/bahar/microblog/app/main/routes.py", line 16, in before_request
    g.locale = str(get_locale())
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_babel/__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "/home/bahar/microblog/app/__init__.py", line 78, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'app' is not defined
2019-07-02 17:22:40,476 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:72]
2019-07-02 17:22:43,755 ERROR: Exception on /auth/login [GET] [in /home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bahar/microblog/app/auth/routes.py", line 28, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/bahar/microblog/app/templates/auth/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/bahar/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/home/bahar/microblog/app/templates/base.html", line 25, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
