2019-07-04 16:42:55,369 ERROR: Exception on /search [GET] [in /home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bahar/microblog/app/main/routes.py", line 127, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/home/bahar/microblog/app/models.py", line 16, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/bahar/microblog/app/search.py", line 23, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 129, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index [post]')
2019-07-04 16:43:44,996 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-04 16:45:26,314 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-04 16:45:28,828 ERROR: Exception on /search [GET] [in /home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bahar/microblog/app/main/routes.py", line 127, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/home/bahar/microblog/app/models.py", line 16, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/bahar/microblog/app/search.py", line 23, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 129, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index [post]')
2019-07-04 16:47:24,454 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-04 16:49:36,764 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-04 16:49:48,091 ERROR: Exception on /search [GET] [in /home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bahar/microblog/app/main/routes.py", line 129, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'dict' and 'int'
2019-07-04 17:20:48,510 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-04 17:26:33,640 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-09 14:58:23,699 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:81]
2019-07-09 17:19:12,784 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:81]
2019-07-09 17:23:36,564 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:81]
2019-07-09 17:43:34,275 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:81]
2019-07-10 13:16:26,241 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:81]
