2019-07-03 15:47:23,460 ERROR: Exception on /explore [GET] [in /home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bahar/microblog/app/main/routes.py", line 119, in explore
    next_url=next_url, prev_url=prev_url)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/bahar/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/bahar/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/home/bahar/microblog/app/templates/base.html", line 36, in block "navbar"
    action="{{ url_for('main.search') }}">
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.search'. Did you mean 'main.user' instead?
2019-07-03 15:48:57,388 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-03 15:49:10,607 ERROR: Exception on /search [GET] [in /home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bahar/microblog/app/main/routes.py", line 130, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'dict' and 'int'
2019-07-03 16:22:17,236 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-03 16:22:21,454 ERROR: Exception on /search [GET] [in /home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bahar/microblog/app/main/routes.py", line 130, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'dict' and 'int'
2019-07-03 16:22:23,632 ERROR: Exception on /search [GET] [in /home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bahar/microblog/app/main/routes.py", line 130, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'dict' and 'int'
